app/models.py
# _*_ encoding: utf-8 _*_
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from . import db, login_manager


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.String(64), unique=True, index=True)
    pin = db.Column(db.String(64))
    username = db.Column(db.String(64))

    isadm=db.Column(db.Boolean,default=False)

    bujuans = db.relationship('Bujuan', backref='user', lazy='dynamic')

    def __repr__(self):
        return '<User %r>' % self.username


    def verify_pin(self, pin):
        return self.pin == pin

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


class Xiangmu(db.Model):
    __tablename__ = 'xiangmus'
    id = db.Column(db.Integer, primary_key=True)
    xiangmu = db.Column(db.String(64))
    bujuans = db.relationship('Bujuan', backref='xiangmu', lazy='dynamic')

    def __repr__(self):
        return '<Xiangmu %r>' % self.xiangmu

class Bujuan(db.Model):
    __tablename__ = 'bujuans'
    id = db.Column(db.Integer, primary_key=True)
    #xiangmu = db.Column(db.String(64))
    jine = db.Column(db.Integer)
    outtime = db.Column(db.DateTime(), default=datetime.utcnow)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    xiangmu_id = db.Column(db.Integer, db.ForeignKey('xiangmus.id'))

    def __repr__(self):
        return '<Bujuan %r>' % self.id

app/main/forms.py
# _*_ encoding: utf-8 _*_
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, InputRequired
from ..models import Xiangmu

class NameForm(FlaskForm):
    #xiangmu = StringField("布放项目", validators=[DataRequired()])
    #xiangmu = SelectField('布放项目', validators=[DataRequired()] , choices=[('0', '放生'),('1', '火施'),('2', '其他')])
    xiangmu = SelectField('布施项目', validators=[DataRequired()] , coerce=int)
    jine = IntegerField("金额", validators=[DataRequired()])
    submit = SubmitField('捐出')

    #在构造化Form实例时指定selectField的choices内容,
    def __init__(self, *args, **kwargs):
        super(NameForm, self).__init__( *args,**kwargs)
        self.xiangmu.choices = [(xiangmu.id, xiangmu.xiangmu) for xiangmu in Xiangmu.query.order_by(Xiangmu.id).all()]

#class EditProfileForm(FlaskForm):

app/__init__.py
# _*_ encoding: utf-8 _*_
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy

from config import config

moment=Moment()
bootstrap=Bootstrap()
db=SQLAlchemy()

login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

def create_app(config_name):
    app=Flask(__name__)

    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    moment = Moment(app)
    bootstrap = Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')
    #...

    return app

app/main/__init__.py
# _*_ encoding: utf-8 _*_
from flask import Blueprint


main=Blueprint('main',__name__)

# @main.app_context_processor
# def inject_permissions():
#     return  dict(Permission=Permission)

from . import views

app/main/views.py
# _*_ encoding: utf-8 _*_
from flask import redirect, url_for, render_template, flash
from flask_login import current_user, login_required
from sqlalchemy import func, engine

from app.models import User, Bujuan, Xiangmu
from .. import db
from .forms import NameForm
from . import main


@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = NameForm()
    # bujuan=None
    bujuans = Bujuan.query.filter_by(user=current_user._get_current_object()).order_by(Bujuan.outtime.desc())

    user = current_user._get_current_object()
    if form.validate_on_submit():
        xiangmu = Xiangmu.query.get(form.xiangmu.data)

        bujuan = Bujuan(user=user, xiangmu=xiangmu, jine=form.jine.data)
        db.session.add(bujuan)
        flash('捐出成功')
        return redirect(url_for('.index'))

    # 管理账号转到管理页
    if user.isadm:
        return redirect(url_for('main.count'))
    else:
        # 一般用户转转到首页..
        return render_template('index.html', form=form, bujuans=bujuans)


#
# @main.route('/list')
# def list():
#     bujuans=Bujuan.query.order_by(Bujuan.outtime.desc())
#     return render_template('list.html', bujuans=bujuans)

# @main.route('/user/<username>')
# def user(username):

@main.route('/count')
@login_required
def count():

    countbujuans = db.session.query(Xiangmu.xiangmu, db.func.sum(Bujuan.jine),Xiangmu.id).join(Bujuan).group_by(
        Xiangmu.xiangmu).all()


    alls = db.session.query(db.func.sum(Bujuan.jine)).all()


    countbujuanbyusers = db.session.query(Xiangmu.xiangmu, User.username,db.func.sum(Bujuan.jine)).join(Bujuan).join(User).group_by(
        Xiangmu.xiangmu, Bujuan.user).all()

    return render_template('count.html', bujuans=countbujuans, alls=alls,countbujuanbyusers=countbujuanbyusers)

@main.route('/countlist/<int:xiangmuid>')
@login_required
def countlist(xiangmuid):

    alls = db.session.query(db.func.sum(Bujuan.jine)).all()


    countbujuanbyusers = db.session.query(Xiangmu.xiangmu, User.username,db.func.sum(Bujuan.jine)).join(Bujuan).join(User).group_by(
        Xiangmu.xiangmu, User.id).having(Bujuan.xiangmu_id==xiangmuid).all()

    return render_template('countlist.html', alls=alls,countbujuanbyusers=countbujuanbyusers)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}乐善好施{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">乐善好施</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                <!--li><a href="{{ url_for('main.index') }}">主页</a></li-->
                <li><a href="{{ url_for('auth.change_username') }}">注册姓名</a></li>
                <li><a href="{{ url_for('auth.logout') }}">登出</a></li>
                {% endif %}

                {% if current_user.is_authenticated and current_user.isadm %}
                    <li><a href="{{ url_for('admin.index') }}">管理数据</a></li>
                {% endif %}


            </ul>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
        <!--使用中文,默认是英语的-->
　　{{ moment.lang("zh-CN") }}

{% endblock %}

app/templates/count.html
{% extends "base.html" %}


{% block title %} To-Do {% endblock %}

{% block page_content %}
    <div class="page-header">
    <h3>{{ current_user.username }}</h3>
        <p>心怀众生</p>
    </div>



<table class="table">
  <thead>
    <tr>
      <th>项目</th>
      <th>金额</th>

    </tr>
  </thead>
  <tbody>

    {% for bujuan in bujuans %}
    <tr>
      <td><a href="{{ url_for('main.countlist',xiangmuid= bujuan[2]) }}">{{ bujuan[0] }}</a></td>
      <td>{{ bujuan[1] }}</td>
    </tr>
    {% endfor %}
    <tr>
      <td class="text-right">总计</td>
      <td>( {{ alls[0][0] }} )</td>
    </tr>
  </tbody>
</table>

<!--table class="table">
  <thead>
    <tr>
      <th>项目</th>
      <th>用户</th>
      <th>金额</th>
    </tr>
  </thead>
  <tbody>

    {% for countbujuanbyuser in countbujuanbyusers %}
    <tr>
      <td>{{ countbujuanbyuser[0] }}</td>
      <td>{{ countbujuanbyuser[1] }}</td>
      <td>{{ countbujuanbyuser[2] }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table-->
{% endblock %}

app/templates/countlist.html
{% extends "base.html" %}


{% block title %} To-Do {% endblock %}

{% block page_content %}
    <!--div class="page-header">
    <h3>{{ current_user.username }}</h3>
        <p>心怀众生</p>
    </div-->

<h4>项目： {{ countbujuanbyusers[0][0] }}</h4>
<table class="table">
  <!--thead>
    <tr>
      <th>项目</th>
      <th>用户</th>
      <th>金额</th>
    </tr>
  </thead-->
  <tbody>

    {% for countbujuanbyuser in countbujuanbyusers %}
    <tr>
      <!--td>{{ countbujuanbyuser[0] }}</td-->
      <td>{{ countbujuanbyuser[1] }}</td>
      <td>{{ countbujuanbyuser[2] }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} To-Do {% endblock %}

{% block page_content %}
    <div class="page-header">
    <h3>{{ current_user.username }}</h3>
        <p>心怀众生</p>
    </div>

    <div>
        {{ wtf.quick_form(form) }}
    </div>


<table class="table">
  <thead>
    <tr>
      <th>项目</th>
      <th>金额</th>
      <!--th>日期</th-->
      <th>经过</th>
    </tr>
  </thead>
  <tbody>

    {% for bujuan in bujuans %}
    <tr>
      <td>{{ bujuan.xiangmu.xiangmu }}</td>
      <td>{{ bujuan.jine }}</td>
      <!--td>{{ moment(bujuan.outtime).format('YY年M月D日') }}</td-->
      <td>{{ moment(bujuan.outtime).fromNow(refresh=True) }}{% if loop.first %}<!--span class="badge">新</span-->{% endif %}</td>

    </tr>

    {% endfor %}
  </tbody>
</table>

{% endblock %}

app/templates/list.html
{% extends "base.html" %}

{% block title %} list {% endblock %}

{% block page_content %}
    <div class="page-header">
    <h3>您的历次捐赠</h3>
    </div>

<table class="table">
  <thead>
    <tr>
      <th>项目</th>
      <th>数量</th>
      <th>日期</th>
    </tr>
  </thead>
  <tbody>

    {% for bujuan in bujuans %}
    <tr>
      <td>{{ bujuan.xiangmu }}</td>
      <td>{{ bujuan.jine }}</td>
        <td>
            {% if loop.first %}<span class="badge">新</span>{% endif %}
            {{ moment(bujuan.outtime).format('YY年M月D日') }}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>


{% endblock %}